repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-yaml
    - id: double-quote-string-fixer
    - id: check-shebang-scripts-are-executable
    - id: check-executables-have-shebangs
    - id: detect-private-key
    - id: detect-aws-credentials

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    - id: script-must-have-extension
    - id: git-dirty
    - id: git-check
    - id: forbid-binary

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: 645165368711be670d1945c15060e746f5ed15c6
    hooks:
    - id: go-fmt
    - id: go-revive
      args: [--config=revive.toml]
