name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Install revive
      run: go install github.com/mgechev/revive@latest

    - name: Format
      run: make format

    - name: Lint
      run: make lint

    - name: Test
      run: make test
